### PR TITLE
Run a Node

### PR DESCRIPTION
**Pull request by CJBangert**
## What

- added diagram
- revised language
- re-structured to match the spec
- re-formatted screenshots on deposits page to be smaller
- outsourced much of the setup instructions to the corresponding client's official docs

## Refs
https://github.com/gnosischain/developers-portal/issues/19

### CODE REVIEW

**Comment by alebanzas** [comment]
Hi @CJBangert thanks for your contribution! The bullets in the description of the PR are meant to be filled with the information related to this PR. Also, in the title you could specify that is a draft by putting the "WIP" prefix.

**Comment by dan-gnosis** [comment]
Comments from review session
- Needs more "client-focused" tutorials (i.e. setup Teku node)
- Should reuse as much as possible from Ethereum

**Comment by alebanzas** [comment]
@CJBangert now that you have the "tools" section merged, please check the following:
- all "https://developers.gnosischain.com" links point to tools, they should point to internally in the project "/tools/..."
- update Dune analytics page with the work you and @nitric made
- add when necessary more internal links to tools in the "run a node" section
Thanks!!

**Review by alebanzas — APPROVED** [review]
lgtm, thanks @CJBangert !!

**Pull request merged**
