### PR TITLE
Create LICENCE-FR

### PR DESCRIPTION
**Pull request by solowmow**
Here's a revised version of the licence in French according to the standards for translating legal documents. Hoping that the effort made will meet your expectations.

## What

- (describe the changes in detail)

## Refs

- (this project accepts pull requests related to open issues)
- (if suggesting a new feature or change, please discuss it in an issue first)
- (if fixing a bug, there should be an issue describing it with steps to reproduce)
- (only fixing a minor bug - broken link, typo - an issue is not needed)
- (please link to the issue here)

### CODE REVIEW

**Comment by dapplion** [comment]
Most github projects expose a single language in english. Can you motivate the need to include translated licenses?

**Comment by solowmow** [comment]
Of course. I am a citizen of the Republic of Benin. The adoption of cryptocurrencies is in its early stages in Francophone African countries. Many, especially computer science students interested in cryptography and databases, are attempting to comprehend the workings of certain protocols through reading. I intend. if you allow it, to produce a comprehensive translation of the documentation from the GitHub repository and some others that my community is interested in, while retaining the essence, meaning, and terminology of the original texts and syntaxes.

**Comment by dapplion** [comment]
Appreciate the contribution but committing translated LICENSE files would open the door to merging translations for all languages. I want to stand on the policy of having a single file in a universal language (english) in our case, and let readers from other regions to translate with online software on demand.

**Comment by solowmow** [comment]
Indeed, I hadn't considered that. I completely understand now. Furthermore, one thing leading to another, there will be a plethora of merge requests under the guise of linguistic supremacy bias. I have one final inquiry: regarding the documentation on nodes, including CONTRIBUTING, README,... and within codes comments, and guides, would you be in favor of the idea of translating them into French?

**Comment by zengzengzenghuy** [comment]
No, we don't have that plan right now. 
Closing this PR.

**Pull request closed without merging**
