### PR TITLE
Doc/#134 update bridges limits xDai, omnibridge

### PR DESCRIPTION
**Pull request by tloffler**
## What

- Update limits on [Omnibridge](https://docs.gnosischain.com/bridges/tokenbridge/omnibridge) and [xDai](https://docs.gnosischain.com/bridges/tokenbridge/xdai-bridge) Bridges doc pages

##  Type of change
- Documentation update

Issue: [Update Documentation for Bridge Limits on xDai and Gnosis](https://github.com/gnosischain/pm/issues/134)

### CODE REVIEW

**Comment by alebanzas** [comment]
@tloffler thanks for the update!!

Could you please specify here how to get the information? So, in the future, we have documented the process of getting the updated values.

**Comment by marianoclaveria** [comment]
> 

The information is added [here](https://docs.google.com/spreadsheets/d/1ZcaBVSR0Xz_MAlK0LASgL-3xp-rucX0-wBmkIg6ImH4/edit#gid=452382875).  Anyway, I can add instructions so anyway can take a look.

**Comment by alebanzas** [comment]
> > 
> 
> The information is added [here](https://docs.google.com/spreadsheets/d/1ZcaBVSR0Xz_MAlK0LASgL-3xp-rucX0-wBmkIg6ImH4/edit#gid=452382875). Anyway, I can add instructions so anyway can take a look.

Thanks @marianoclaveria ! Do you have a `script` or `query` to get the updated info?

**Comment by marianoclaveria** [comment]
> > > 
> > 
> > 
> > The information is added [here](https://docs.google.com/spreadsheets/d/1ZcaBVSR0Xz_MAlK0LASgL-3xp-rucX0-wBmkIg6ImH4/edit#gid=452382875). Anyway, I can add instructions so anyway can take a look.
> 
> Thanks @marianoclaveria ! Do you have a `script` or `query` to get the updated info?

No. The values were calculated reading the contracts manually. The monitoring tool was supposed to provide those values. Anyway, I will add the steps made for manual checking. Thanks for asking!

**Comment by alebanzas** [comment]
I will merge the PR. @marianoclaveria please, add the steps in a comment in this thread for future reference! Thanks!

**Review by alebanzas — APPROVED** [review]
LGTM, thanks @tloffler !

**Pull request merged**
